### ISSUE TITLE
Model creation does not take Postgres schema into account

### ISSUE THREAD

**Issue by tsnork** [timhaak/reliese-laravel-models#1]
Hey,

thanks for forking the model creation tool to make it compatible with Postgres.

There still seems to be a minor issue with model creation for Postgres:

Suppose you have some models in a different schema than Postgres default:

`_schema.table1`

The model creator loops through all schemas and creates a model like this:

```
class Table1 extends \Illuminate\Database\Eloquent\Model
{
	protected $table = 'table1';
```

If you try to query this Model like this:

`$values = db\Table1::all();`

You get the following error:

`SQLSTATE[42P01]: Undefined table: 7 ERROR: relation "table1" does not exist LINE 1: select * from "table1" ^ (SQL: select * from "table1")`

You can fix this by editing the Model definition like this:

```
class Table1 extends \Illuminate\Database\Eloquent\Model
{
	protected $table = '_schema.table1';
```

I edited all my files accordingly, but it'd be great if this could be fixed in code. 

Thanks for your help in advance and again for the fork!

**Comment by timhaak** [comment]
Hi

Will double-check this.

Just want to confirm that you have set

`'qualified_tables' => true,`

Which currently fixes that my side. (It may have the wrong setting but think it's that one)

Check the opensource project bellow where I'm using this library.

https://github.com/haakco/haakco-api
https://github.com/haakco/haakco-api/blob/master/app/Models/File.php

Here is the config for the project 

https://github.com/haakco/haakco-api/blob/master/config/models.php

**Comment by tsnork** [comment]
Wow. I'm sorry - I read that models.php config about 30 times, because I was sure there'd be an option. And there it is. Don't know why I didn't see this. I'll close this and get my cone of shame. ;)

Thanks for your quick reply. :)

**Comment by timhaak** [comment]
Not a problem :) It's named more for MySQL than what you would call it for postgres
